name 'stephenrjohnson-puppet'
version '0.0.13'
source 'git://github.com/stephenrjohnson/puppetlabs-puppet.git'
author 'Stephen Johnson'
description 'Resource types for managing puppet master and agent'
summary 'Resource types for managing puppet master and agent'
license 'Apache'
project_page 'https://github.com/stephenrjohnson/puppetlabs-puppet'
## Add dependencies, if any:
dependency 'cprice404/inifile', '>= 0.5.0'
dependency 'puppetlabs/apache', '>= 0.8.0'
dependency 'puppetlabs/puppetdb', '>= 1.1.5'
